# Generated by Django 3.0.5 on 2021-10-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211023_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('user', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Secret',
            },
        ),
    ]
