# Generated by Django 3.0.5 on 2021-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
